-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bookings (
  loc text NOT NULL,
  fecha_registro_venta timestamp with time zone,
  fecha_salida_vuelo date,
  origen_codigo text,
  destino_codigo text,
  ruta_completa text,
  numero_vuelo text,
  aerolinea text,
  paradas_o_escalas text,
  duracion_vuelo text,
  equipaje_incluido text,
  estado_reserva text,
  tipo_servicio text,
  proveedor text,
  agente_venta text,
  pax_total integer,
  pasajeros_nombres text,
  pasajeros_ticket_numbers text,
  venta_total_usd numeric,
  costo_base_usd numeric,
  emision_fee_usd numeric,
  hostal_usd numeric,
  fee_agencia_usd numeric,
  total_boleto_usd numeric,
  vuelto_usd numeric,
  pago_status text,
  metodo_pago text,
  cuenta_pago text,
  last_updated_source text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (loc)
);
CREATE TABLE public.bot_stats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bot_id uuid,
  date date DEFAULT CURRENT_DATE,
  messages_sent integer DEFAULT 0,
  messages_received integer DEFAULT 0,
  media_sent integer DEFAULT 0,
  media_received integer DEFAULT 0,
  errors_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bot_stats_pkey PRIMARY KEY (id),
  CONSTRAINT bot_stats_bot_id_fkey FOREIGN KEY (bot_id) REFERENCES public.bots(id)
);
CREATE TABLE public.bots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  phone_number text NOT NULL,
  status text DEFAULT 'offline'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  session_name text UNIQUE,
  engine text DEFAULT 'NOWEB'::text,
  qr_code text,
  last_seen timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  worker_id uuid,
  CONSTRAINT bots_pkey PRIMARY KEY (id),
  CONSTRAINT bots_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id)
);
CREATE TABLE public.chats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bot_id uuid,
  contact_number text NOT NULL,
  contact_name text,
  unread_count integer DEFAULT 0,
  last_message text,
  last_message_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  chat_id text,
  contact_id uuid,
  is_group boolean DEFAULT false,
  archived boolean DEFAULT false,
  pinned boolean DEFAULT false,
  muted boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  last_message_time timestamp with time zone,
  name character varying,
  ai_analysis jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT chats_pkey PRIMARY KEY (id),
  CONSTRAINT chats_bot_id_fkey FOREIGN KEY (bot_id) REFERENCES public.bots(id),
  CONSTRAINT chats_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.contact_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contact_id uuid,
  note text NOT NULL,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_notes_pkey PRIMARY KEY (id),
  CONSTRAINT contact_notes_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.contact_tags (
  contact_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_tags_pkey PRIMARY KEY (contact_id, tag_id),
  CONSTRAINT contact_tags_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT contact_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bot_id uuid,
  phone_number text NOT NULL,
  name text,
  push_name text,
  is_business boolean DEFAULT false,
  is_enterprise boolean DEFAULT false,
  profile_picture_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_bot_id_fkey FOREIGN KEY (bot_id) REFERENCES public.bots(id)
);
CREATE TABLE public.conversation_evaluations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chat_id uuid NOT NULL,
  bot_id uuid NOT NULL,
  worker_id uuid,
  evaluation_date timestamp with time zone DEFAULT now(),
  generated_by text NOT NULL,
  manually_edited boolean DEFAULT false,
  evaluated_by_user_id uuid,
  tiempo_contacto boolean DEFAULT false,
  tiempo_respuesta boolean DEFAULT false,
  tiempo_cotizacion boolean DEFAULT false,
  cierre_intencion boolean DEFAULT false,
  ofrecio_scalapay boolean DEFAULT false,
  mas_dos_opciones boolean DEFAULT false,
  seguimiento_intencion boolean DEFAULT false,
  score integer NOT NULL DEFAULT 0,
  max_score integer NOT NULL DEFAULT 7,
  percentage numeric NOT NULL DEFAULT 0.00,
  ai_feedback text,
  manager_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  performance_analysis_id uuid,
  venta_confirmada boolean DEFAULT false,
  lead_caliente boolean DEFAULT false,
  cotizacion_enviada boolean DEFAULT false,
  metodo_pago_enviado boolean DEFAULT false,
  objeciones_superadas boolean DEFAULT false,
  seguimiento_efectivo boolean DEFAULT false,
  urgencia_creada boolean DEFAULT false,
  valor_agregado boolean DEFAULT false,
  score_ventas integer DEFAULT 0,
  percentage_ventas numeric DEFAULT 0.00,
  valor_venta numeric,
  valor_estimado numeric,
  interest_level character varying DEFAULT 'bajo'::character varying CHECK (interest_level::text = ANY (ARRAY['alto'::character varying, 'medio'::character varying, 'bajo'::character varying]::text[])),
  resultado_comercial jsonb DEFAULT '{}'::jsonb,
  exitos_asesor ARRAY,
  errores_criticos ARRAY,
  siguiente_accion text,
  confidence_score numeric DEFAULT 0.00 CHECK (confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  analysis_method character varying DEFAULT 'hybrid'::character varying,
  analysis_version character varying DEFAULT 'v2.0'::character varying,
  CONSTRAINT conversation_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_evaluations_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id),
  CONSTRAINT conversation_evaluations_bot_id_fkey FOREIGN KEY (bot_id) REFERENCES public.bots(id),
  CONSTRAINT conversation_evaluations_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id),
  CONSTRAINT conversation_evaluations_evaluated_by_fkey FOREIGN KEY (evaluated_by_user_id) REFERENCES public.profiles(id),
  CONSTRAINT conversation_evaluations_performance_analysis_id_fkey FOREIGN KEY (performance_analysis_id) REFERENCES public.performance_analyses(id)
);
CREATE TABLE public.daily_sales_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asesor_id uuid NOT NULL,
  worker_id uuid,
  report_date date NOT NULL,
  ventas_confirmadas integer DEFAULT 0 CHECK (ventas_confirmadas >= 0),
  leads_calientes integer DEFAULT 0,
  cotizaciones_enviadas integer DEFAULT 0,
  conversaciones_analizadas integer DEFAULT 0,
  valor_total_ventas numeric DEFAULT 0.00,
  tasa_conversion numeric DEFAULT 0.00 CHECK (tasa_conversion >= 0::numeric AND tasa_conversion <= 100::numeric),
  valor_promedio_venta numeric DEFAULT 0.00,
  score_promedio_ventas numeric DEFAULT 0.00,
  nivel_rendimiento character varying DEFAULT 'REGULAR'::character varying,
  requiere_seguimiento boolean DEFAULT false,
  ventas_exitosas jsonb DEFAULT '[]'::jsonb,
  oportunidades_perdidas jsonb DEFAULT '[]'::jsonb,
  recomendaciones jsonb DEFAULT '[]'::jsonb,
  performance_analysis_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_sales_reports_pkey PRIMARY KEY (id),
  CONSTRAINT daily_sales_reports_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id),
  CONSTRAINT daily_sales_reports_performance_analysis_id_fkey FOREIGN KEY (performance_analysis_id) REFERENCES public.performance_analyses(id)
);
CREATE TABLE public.media_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bot_id uuid,
  message_id uuid,
  file_url text NOT NULL,
  file_name text,
  mimetype text,
  file_size bigint,
  thumbnail_url text,
  created_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT media_files_pkey PRIMARY KEY (id),
  CONSTRAINT media_files_bot_id_fkey FOREIGN KEY (bot_id) REFERENCES public.bots(id),
  CONSTRAINT media_files_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bot_id uuid,
  message_id text NOT NULL,
  from_number text NOT NULL,
  to_number text NOT NULL,
  content text,
  media_url text,
  message_type text NOT NULL,
  status text,
  timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  chat_id uuid,
  contact_id uuid,
  body text,
  type text DEFAULT 'text'::text,
  from_me boolean DEFAULT false,
  ack integer DEFAULT 0,
  has_media boolean DEFAULT false,
  media_mimetype text,
  caption text,
  quoted_message_id text,
  is_forwarded boolean DEFAULT false,
  broadcast boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_bot_id_fkey FOREIGN KEY (bot_id) REFERENCES public.bots(id),
  CONSTRAINT messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id),
  CONSTRAINT messages_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.performance_analyses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  analysis_name text NOT NULL,
  bot_id uuid NOT NULL,
  worker_id uuid,
  total_conversations_analyzed integer NOT NULL DEFAULT 0,
  average_score numeric NOT NULL DEFAULT 0.00,
  average_percentage numeric NOT NULL DEFAULT 0.00,
  tiempo_contacto_count integer DEFAULT 0,
  tiempo_respuesta_count integer DEFAULT 0,
  tiempo_cotizacion_count integer DEFAULT 0,
  cierre_intencion_count integer DEFAULT 0,
  ofrecio_scalapay_count integer DEFAULT 0,
  mas_dos_opciones_count integer DEFAULT 0,
  seguimiento_intencion_count integer DEFAULT 0,
  generated_by text NOT NULL,
  created_by_user_id uuid,
  status text DEFAULT 'draft'::text,
  general_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  finalized_at timestamp with time zone,
  analysis_date date NOT NULL DEFAULT CURRENT_DATE,
  ventas_confirmadas_count integer DEFAULT 0,
  leads_calientes_count integer DEFAULT 0,
  valor_total_ventas numeric DEFAULT 0.00,
  tasa_conversion numeric DEFAULT 0.00,
  average_score_ventas numeric DEFAULT 0.00,
  nivel_comercial character varying DEFAULT 'REGULAR'::character varying,
  sales_summary jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT performance_analyses_pkey PRIMARY KEY (id),
  CONSTRAINT performance_analyses_bot_id_fkey FOREIGN KEY (bot_id) REFERENCES public.bots(id),
  CONSTRAINT performance_analyses_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id),
  CONSTRAINT performance_analyses_created_by_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.performance_improvements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id uuid NOT NULL,
  performance_analysis_id uuid,
  parameter_name text NOT NULL,
  improvement_suggestion text NOT NULL,
  priority text DEFAULT 'medium'::text,
  status text DEFAULT 'pending'::text,
  assigned_to_user_id uuid,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT performance_improvements_pkey PRIMARY KEY (id),
  CONSTRAINT performance_improvements_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id),
  CONSTRAINT performance_improvements_analysis_id_fkey FOREIGN KEY (performance_analysis_id) REFERENCES public.performance_analyses(id),
  CONSTRAINT performance_improvements_assigned_to_fkey FOREIGN KEY (assigned_to_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.performance_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  performance_analysis_id uuid NOT NULL,
  report_type text NOT NULL,
  report_name text NOT NULL,
  file_url text,
  file_size bigint,
  include_details boolean DEFAULT true,
  include_conversations boolean DEFAULT false,
  include_charts boolean DEFAULT true,
  generated_by_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  downloaded_at timestamp with time zone,
  report_data jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT performance_reports_pkey PRIMARY KEY (id),
  CONSTRAINT performance_reports_analysis_id_fkey FOREIGN KEY (performance_analysis_id) REFERENCES public.performance_analyses(id),
  CONSTRAINT performance_reports_generated_by_fkey FOREIGN KEY (generated_by_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  full_name character varying,
  role_id uuid,
  worker_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT profiles_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  permissions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sales_analysis_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  config_key character varying NOT NULL UNIQUE,
  config_value jsonb NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_analysis_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sales_analysis_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type character varying NOT NULL,
  asesor_id uuid,
  worker_id uuid,
  event_data jsonb DEFAULT '{}'::jsonb,
  success boolean DEFAULT true,
  error_message text,
  execution_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_analysis_logs_pkey PRIMARY KEY (id),
  CONSTRAINT sales_analysis_logs_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id)
);
CREATE TABLE public.tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bot_id uuid,
  name text NOT NULL,
  color text DEFAULT '#3B82F6'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tags_pkey PRIMARY KEY (id),
  CONSTRAINT tags_bot_id_fkey FOREIGN KEY (bot_id) REFERENCES public.bots(id)
);
CREATE TABLE public.tasas_monedas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  moneda_codigo text NOT NULL UNIQUE,
  moneda_nombre text NOT NULL,
  simbolo text NOT NULL DEFAULT '$'::text,
  tasa_conversion numeric NOT NULL DEFAULT 1.0,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_by uuid,
  CONSTRAINT tasas_monedas_pkey PRIMARY KEY (id),
  CONSTRAINT tasas_monedas_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bot_id uuid,
  event_type text NOT NULL,
  event_data jsonb NOT NULL,
  processed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  CONSTRAINT webhook_events_pkey PRIMARY KEY (id),
  CONSTRAINT webhook_events_bot_id_fkey FOREIGN KEY (bot_id) REFERENCES public.bots(id)
);
CREATE TABLE public.workers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  phone_number character varying,
  role character varying DEFAULT 'agent'::character varying,
  status character varying DEFAULT 'active'::character varying,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_active timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT workers_pkey PRIMARY KEY (id)
);